services:
  - type: web
    name: pharmadb-research-agent
    env: docker
    plan: free # Or your preferred plan, e.g., starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Keep value in Render dashboard
      - key: BING_KEY
        sync: false # Keep value in Render dashboard
      # - key: REDIS_URL # Temporarily commented out until Render Redis is confirmed/set up
      #   fromService:
      #     type: redis
      #     name: pharmadb-redis # Ensure this matches your Render Redis service name
      - key: PYTHON_VERSION
        value: "3.12" # Matches Dockerfile
      # - key: PORT # Removed to let Render inject its own PORT variable
      - key: RESEARCH_AGENT_API_KEY # For securing your microservice
        sync: false # Keep value in Render dashboard
      # Add other necessary environment variables here
    autoDeploy: true # Optional: automatically deploy on push to main branch
    healthCheckPath: /healthz # T12: Add health check path
    # Optional: Define build instance type if needed
    # buildInstanceType: standard 
    # Optional: Define instance count
    # numInstances: 1

# Example Redis instance (if you create one on Render)
# - type: redis
#   name: pharmadb-redis # Must match the name used in fromService above
#   plan: free # Or your preferred plan
#   ipAllowList: [] # Configure as needed, e.g., ["0.0.0.0/0"] for open access (not recommended for prod)
#   maxmemoryPolicy: allkeys-lru 