services:
  - type: web
    name: pharmadb-research-agent
    env: docker
    plan: free # Or your preferred plan, e.g., starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Keep value in Render dashboard
      - key: BING_KEY
        sync: false # Keep value in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: red-d0uhh5m3jp1c7382sq30
      - key: PYTHON_VERSION
        value: "3.12" # Matches Dockerfile
      # - key: PORT # Removed to let Render inject its own PORT variable
      - key: 9620da7297830073ae2fb449b14e908b
        sync: false # Keep value in Render dashboard
      # Add other necessary environment variables here
    autoDeploy: true # Optional: automatically deploy on push to main branch
    healthCheckPath: /healthz # T12: Add health check path
    # Optional: Define build instance type if needed
    # buildInstanceType: standard 
    # Optional: Define instance count
    # numInstances: 1

# Example Redis instance (if you create one on Render)
- type: redis
  name: red-d0uhh5m3jp1c7382sq30 # This should match the name of your actual Redis service
  plan: free # Or your preferred plan
  # region: oregon # Optional: ensure same region as web service
  ipAllowList: [] # Configure as needed, e.g., ["0.0.0.0/0"] for open access (not recommended for prod)
  maxmemoryPolicy: allkeys-lru 